/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.watchdog;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;

import android.app.Activity;
import android.content.Context;
import android.os.Build;

@Kroll.module(name = "Watchdogholder", id = "de.appwerft.watchdog")
public class WatchdogModule extends KrollModule {

	public WatchdogModule() {
		super();
	}

	private Watchdog watchdog;
	private static Context ctx;

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		ctx = app.getApplicationContext();
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
			Watchdog watchdog = new Watchdog();
			watchdog.start(ctx);
		}
	}

	public void onDestroy(Activity activity) {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
			watchdog.stopp(ctx);
		}
	}
}
